# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sthiagar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/21 19:54:40 by sthiagar          #+#    #+#              #
#    Updated: 2025/01/21 19:57:39 by sthiagar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    env_file:
      - .env
    image: "${NGINX_IMG:-nginx}"
    
    build:
      context: ./requirements/nginx
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION} #default value in Dockerfile
    container_name: "${NGINX_CONTAINER:-mynginx}"

    ports:
      - "443:443"
    secrets:
      - key
      - cert
    volumes:
      - ./requirements/nginx/html/index.html:/var/www/html/static/index.html #static file
      - wp_files:/var/www/html/wordpress #dynamic files from php-fpm
      - ./requirements/nginx/conf/custom.conf:/etc/nginx/nginx.conf #custom confiq
      - ./requirements/nginx/log:/var/log/nginx #access amd error logs
     
    networks:
      - app-network
    restart: always
    
    depends_on:
      - wordpress

  wordpress:
    env_file:
      - .env
    image: "${WORDPRESS_IMG:-wordpress}"
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    container_name: "${WP_CONTAINER:-mywordpress}"
    environment:
      PHP_FPM_BIND_ADDR: ${PHP_FPM_BIND_ADDR}
      PHP_FPM_PORT: ${PHP_FPM_PORT}
      PHP_VER: ${PHP_VER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wp_user_password"
      WORDPRESS_CONFIG_EXTRA:
        define('WP_HOME', 'https://${DOMAIN_NAME}:${PORT}');
        define('WP_SITEURL', 'https://${DOMAIN_NAME}:${PORT}/wp-admin');
    secrets:
      - wp_user_password
    depends_on:
      - mariadb

    volumes:
      - wp_files:/var/www/html #wordpress files
      - ./requirements/wordpress/log:/var/log/php-fpm.log #php-fpm logs
    networks:
      - app-network
    restart: always

  mariadb:
    env_file:
      - .env
    image: "${MARIADB_IMG:-mariadb}"
    build:
      context: ./requirements/mariadb
      #args:
      #  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: "${MDB_CONTAINER:-mymariadb}"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_USER}
      MYSQL_PASSWORD_FILE: "/run/secrets/wp_user_password"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
    secrets:
      - wp_user_password
      - db_root_password
    volumes:
      #- ./requirements/mariadb/tools/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./requirements/mariadb/tools/:/docker-entrypoint-initdb.d/
      - ./requirements/mariadb/conf/custom.conf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    name: ${APP_NETWORK}
    driver: bridge

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_FILES}
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_DATA}
      
secrets:
  wp_user_password:
    file: ${WORDPRESS_USER_PASSWORD_FILE}
  db_root_password:
    file: ${MYSQL_ROOT_PASSWORD_FILE}
  key:
    file: ${SSL_KEY}
  cert:
    file: ${SSL_CERT}
