# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sthiagar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/21 19:54:40 by sthiagar          #+#    #+#              #
#    Updated: 2025/01/21 19:57:39 by sthiagar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    #image: "${NGINX_IMG:-nginx}"
    build:
      context: ./requirements/nginx
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    depends_on:
      - wordpress
    networks:
      - app-network
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/html/selvam.html:/mnt/html/selvam.html #static file
      - wp_files:/var/www/html
      - ./requirements/nginx/conf/custom.conf:/etc/nginx/nginx.conf #custom confiq
      - ./requirements/nginx/log:/var/log/nginx #access amd error logs
    env_file:
      - .env
    secrets:
      - key
      - cert
    restart: always
    container_name: "${NGINX_CONTAINER:-mynginx}"
  
  wordpress:
    #image: "${WORDPRESS_IMG:-wordpress}"
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - wp_files:/var/www/html #wordpress files
      - ./requirements/wordpress/log:/var/log/ #php-fpm logs
    environment:
      PHP_FPM_BIND_ADDR: ${PHP_FPM_BIND_ADDR}
      PHP_FPM_PORT: ${PHP_FPM_PORT}
      PHP_VER: ${PHP_VER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_SUPER: ${WORDPRESS_SUPER}
      WORDPRESS_REGULAR: ${WORDPRESS_REGULAR}
      WORDPRESS_PASSWORD_FILE: "/run/secrets/db_password"
    env_file:
      - .env
    secrets:
      - db_password
    container_name: "${WP_CONTAINER:-mywordpress}"
    restart: always

  mariadb:
    #image: "${MARIADB_IMG:-mariadb}"
    build:
      context: ./requirements/mariadb
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./requirements/mariadb/tools/:/docker-entrypoint-initdb.d/
      - ./requirements/mariadb/conf/custom.conf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./requirements/mariadb/log:/var/log
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_USER_PASSWORD_FILE: "/run/secrets/db_password"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
         
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    container_name: "${MDB_CONTAINER:-mymariadb}"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    name: ${APP_NETWORK}
    driver: bridge

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_FILES}
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_DATA}
      
secrets:
  db_password:
    file: ${WORDPRESS_PASSWORD_FILE}
  db_root_password:
    file: ${MYSQL_ROOT_PASSWORD_FILE}
  key:
    file: ${SSL_KEY}
  cert:
    file: ${SSL_CERT}
