# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sthiagar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/21 19:54:40 by sthiagar          #+#    #+#              #
#    Updated: 2025/01/21 19:57:39 by sthiagar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#version: I don't need to specify in Docker Compose V2 or newer

services:
  nginx:
    env_file:
      - .env
    image: "${NGINX_IMG:-nginx}"
    
    build:
      context: ./requirements/nginx
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION} #default value in Dockerfile
    container_name: "${NGINX_CONTAINER:-mynginx}"

    ports:
      - "8443:443"  #443 is privileged port
    volumes:
      - ./requirements/nginx/html/index.html:/var/www/html/static/index.html #static file
      - wp_files:/var/www/html/wordpress #dynamic files from php-fpm
      - ./requirements/nginx/conf/custom.conf:/etc/nginx/nginx.conf #custom confiq
      - ./requirements/nginx/log:/var/log/nginx #access amd error logs

    networks:
      - app-network
    restart: always

  wordpress:
    env_file:
      - .env
    image: "${WORDPRESS_IMG:-wordpress}"
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        #WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        #WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        #WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        #WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    container_name: "${WP_CONTAINER:-mywordpress}"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA:
        define('WP_HOME', 'https://${DOMAIN_NAME}:${PORT}');
        define('WP_SITEURL', 'https://${DOMAIN_NAME}:${PORT}/wp-admin');
    depends_on:
      - mariadb
    #ports:
    #  -"9000:9000" #Not exposed. Communicates with NGINX via fastCGI
    volumes:
      - wp_files:/var/www/html #wordpress files
      - ./requirements/wordpress/log:/var/log/php-fpm.log #php-fpm logs
      #- ./wordpress/conf/wp-config.php:/var/www/html/wp-config.php
    networks:
      - app-network
    restart: always

  mariadb:
    env_file:
      - .env
    image: "${MARIADB_IMG:-mariadb}"
    build:
      context: ./requirements/mariadb
      #args:
      #  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: "${MDB_CONTAINER:-mymariadb}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./requirements/mariadb/conf/custom.conf:/etc/mysql/mariadb.conf.d/50-server.cnf
      #- /home/sthiagar/data/mysql_data:/var/lib/mysql
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    name: ${APPNETWORK}
    driver: bridge

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sthiagar/data/wp_files
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sthiagar/data/mysql_data
  
