CREATE DATABASE IF NOT EXISTS __MYSQL_DATABASE__;
DROP USER IF EXISTS '__MYSQL_USER__'@'%';
CREATE USER '__MYSQL_USER__'@'%' IDENTIFIED BY '__MYSQL_USER_PASSWORD__';
GRANT ALL PRIVILEGES ON __MYSQL_DATABASE__ .* TO '__MYSQL_USER__'@'%';
-- Force root to require password
ALTER USER 'root'@'localhost' IDENTIFIED BY '__MYSQL_ROOT_PASSWORD__';
DELETE FROM mysql.user WHERE user='root' AND host NOT IN ('localhost');
FLUSH PRIVILEGES;
