CREATE DATABASE IF NOT EXISTS _MYSQL_DATABASE_;
DROP USER IF EXISTS '_MYSQL_USER_'@'%';
CREATE USER '_MYSQL_USER_'@'%' IDENTIFIED BY '_MYSQL_PASSWORD_';
GRANT ALL PRIVILEGES ON _MYSQL_DATABASE_ .* TO '_MYSQL_USER_'@'%';
FLUSH PRIVILEGES;
